package com.velet.wallet.models.enums;

public enum EventType {
    TRANSFER_COMPLETED,
    LOYALTY_TRANSFER_EVENT,
    BALANCE_RESERVATION_CREATED,
    RESERVATION_CONFIRMED,
    TRANSACTION_CANCELLED,
}